TW-142 Notification page manager side
madfish-solutions/templewallet-backend pull request #105
Opened 2023-06-22 20:14 UTC by lendihop

https://madfish.atlassian.net/jira/software/projects/TW/boards/4?selectedIssue=TW-142

2023-06-26 07:55 UTC, lendihop commented on db.json
> +{
yes. Thats why we need to add it to gitignore after the first deploy

2023-06-30 22:36 UTC, lendihop commented on redis.conf
disables redis RDB and AOF backups, https://redis.io/docs/management/persistence/

2023-06-30 22:41 UTC, lendihop commented on src/notifications/utils/get-notifications.util.ts
> +export const getNotifications = (db: LowdbSync<DbData>, platform: PlatformType, startFromTime: number) => {
the problem is that startFromTime parameter is different for every user, so i suppose we wouldnt get much from such memoization + cache size of this fn would be really big

2023-07-03 15:23 UTC, lourenc requested changes

2023-07-07 12:41 UTC, lourenc requested changes

2023-07-07 12:41 UTC, lourenc commented on src/middlewares/basic-auth.middleware.ts
> +    // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
Can we remove this eslint disable rule? 

In order to do so, you can assign `req.get('Authorization')` to a variable and then use `isDefined` as a typeguard on the variable value.

2023-07-11 10:22 UTC, lourenc approved these changes

2023-07-11 10:22 UTC, merged